version: "3"

services:
  app:
    env_file:
      - ./.env.local
    build:
      context: .
      dockerfile: ~/dev/.dockers/node/
    ports:
      - "8080:8080"
      - "4173:4173"
    volumes:
      - "./front:/var/www/app"
    tty: true
    command: pnpm run preview